# 异常

异常是指程序在执行过程中，出现的非正常情况，如果不处理最终会导致JVM的非正常运行

> *并不是指语法错误和逻辑错误*   如用户输入格式是否正确、读取文件是否存在

Java中把不同的异常用不同的类型表示，一旦发生某种异常，就**创建该异常类型的对象**，并且抛出（throw），然后程序员就要捕捉（catch）这个异常的对象，并处理

## Error和Exception

Error： java虚拟机无法解决的严重问题，无法进行处理，只能进行代码修改

> 如 栈溢出 StackOverflowError  

Exception：其他因编程错误或偶然的外在因素导致的一般问题。可以进行处理

> 编译异常：执行javac.exe命令发生的异常
>
> 运行异常：执行java.exe命令发生的异常

## 常见异常

`ArrayIndexOutOfBoundsException`   数组下标越界

`NullPointerException`  空指针异常

`InputMismatchException`  数据输入异常（输入的数据与需要的数据类型不一致）

`ArithmeticException`  算数异常 （1 / 0）

---------------------------------------------------------------------------------------------------------------------

`ClassNotFoundException` 没有找到类

`FileNotFoundException` 找不到文件



## 异常处理

Java采用的异常处理机制，**将异常处理的程序代码集中在一起**，与正常程序代码分开，使得程序简洁、优雅，并易于维护

### 抓抛模型 try—catch—finally

**“抛”**：程序在执行过程中，一旦出现异常，就会在出现异常的代码处，生成对应异常类的对象，并将此对象抛出。一旦抛出，此程序就不执行其后的代码。

**“抓”**：针对于过程中抛出的异常对象，进行捕获处理。一旦将异常进行了处理，代码就可以继续执行。

基本结构：

``` java 
try{
    ......  //可能产生异常的代码
}
catch(异常类型1 e){
    ......  //异常类型1处理措施
}
catch(异常类型2 e){
    ......  //异常类型2处理措施
}
finally{
    ......  //无论是否发生异常，都无条件执行的语句
}
//finally可以省略
```

使用细节：

> 将可能出现异常的代码声明在try语句中。
>
> 一旦出现异常，就会自动生成对应异常类的对象，并将此对象进行抛出
>
> 针对try抛出的异常类对象，使用之后的catch语句进行匹配，一旦匹配上，就进入catch语句块进行处理
>
> 如果声明了多个catch结构  若不满足子父类关系，则上下顺序不做要求   若满足子父类关系，则父类要声明在下面（如：RuntimeException）

``` java
try{
    Scanner sc = new Scanner(System.in);
    int num = sc.netInt();   // 若输入 abc 则直接进入catch语句
    System.out.println(num);  // 出现异常后该语句不执行
}catch(InputMismatchException e){
    System.out.println("输入错误");  //直接进入此语句中
}

......  //继续执行下方语句
```

catch异常处理方式：

> ①  自己编写输出语句
>
> ②  `printStackTrace()`  自带方法 --> 打印异常的详细信息   √
>
> ③  `getMessage()`  获取发生异常的原因

``` java
try{
    ......
}catch(InputMismatchException e){
    e.printStackTrace();
}
```

！！！注：try中定义的变量，出了try结构之后，就不可以再调用了

try—catch结构可以嵌套使用



### Finally的使用

我们将一定要被执行的代码写到finally语句里面

> 无论try或catch中是否存在未被处理的异常，无论try或catch中是否存在return语句，finally中声明的语句一定会被执行

finally语句不能单独使用

eg1.

``` java
public static void main(String[] args){
	int result = test("a");
	System.out.println(result);
}

public static int test(String s){
	try{
		Integer.parseInt(s);
		return 1;
	}catch(Exception e){
		return -1;
	}finally{
		System.out.println("lalala");
		return 0;     //最终的返回值
	}
}
//最终结果：lalala
           0
```

eg2.

```java
public static void main(String[] args){
	int result = test(10);
	System.out.println(result);
}

public static int test(int num){
	try{
		return num
	}catch(Exception e){
		return -1;
	}finally{
		System.out.println("lalala");
		++ num;
	}
}
//最终结果：lalala
           10
```

**解释**：执行完try里的语句后，return的number被放到了操作性栈里，num的值为10，接下来执行finally里的语句，num ++ 到了11，但此时操作性栈里放的返回值仍然是10，所以最后返回的值为10

**！！！** 若try或catch里含有` System.exit(0)`，程序会被强行终止，finally里语句不会执行

> 在开发中，有一些资源：输入输出流、数据库连接等，在使用完以后，必须**显示的**进行关闭操作，否则垃圾回收器不会自动回收这些资源，进而导致内存的泄露
>
> 为了保证这些资源使用完之后，不管是否出现异常，这些资源都能被关闭，我们把这些操作放到finally语句中



### throws

基本格式：

``` java
public void test() throws 异常类型1 异常类型2...{
    ......
}
```

**方法重写时**

> 子类中方法抛出的异常只能和父类中方法抛出的异常一致或者是父类中方法抛出异常的子类
>
> 若父类中方法没有抛出异常，子类方法中也不能抛出异常



